# Collect every .c under src/ (recursively)
file(GLOB_RECURSE SRCS
     RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
     "src/*.c")

idf_component_register(
    SRCS ${SRCS}
        
    INCLUDE_DIRS 
    	"include"
    
    REQUIRES
    	common
    
    PRIV_REQUIRES
    	lora sx126x esp_adc efuse esp_timer esp_driver_gpio esp_driver_spi
)